/**
 * Residential material catalog.
 *
 * This is the single source of truth for orderable parts. Every PartLine in the
 * system must resolve to an entry here. Unknown free-text items are never stored.
 *
 * SKU conventions:
 *   LUM-  lumber and engineered wood
 *   SHT-  sheathing / panel products
 *   DRY-  drywall products
 *   INS-  insulation
 *   ELE-  electrical
 *   PLM-  plumbing
 *   HVA-  HVAC
 *   CON-  concrete / masonry
 *   FAS-  fasteners
 *   ROO-  roofing / envelope
 *   FIN-  finish materials (paint, trim, flooring)
 *   FIX-  fixtures and appliances
 *   HRD-  structural hardware (hangers, ties)
 *
 * Costs are rough residential averages (USD) — order-of-magnitude correct, not
 * contract pricing. They are informational; the app does not guarantee them.
 */

import { stageDef } from "./stages";
import type { PartCategory, PartLine, StageId } from "./types";

export type CatalogEntry = {
  sku: string;
  name: string;
  category: PartCategory;
  unit: PartLine["unit"];
  spec?: string;
  unitCostUsd?: number;
};

export const CATALOG: Record<string, CatalogEntry> = {
  // ─── LUMBER & STRUCTURAL ──────────────────────────────────────────────────
  "LUM-2X4-92": {
    sku: "LUM-2X4-92",
    name: "2x4 stud",
    category: "lumber",
    unit: "ea",
    spec: "92-5/8in precut SPF",
    unitCostUsd: 4.28,
  },
  "LUM-2X4-PLATE": {
    sku: "LUM-2X4-PLATE",
    name: "2x4 plate stock",
    category: "lumber",
    unit: "lf",
    spec: "SPF, top and bottom plates",
    unitCostUsd: 0.72,
  },
  "LUM-2X6-92": {
    sku: "LUM-2X6-92",
    name: "2x6 stud",
    category: "lumber",
    unit: "ea",
    spec: "92-5/8in precut SPF",
    unitCostUsd: 6.85,
  },
  "LUM-2X6-PT": {
    sku: "LUM-2X6-PT",
    name: "2x6 PT plate stock",
    category: "lumber",
    unit: "lf",
    spec: "pressure-treated, sill and bottom plate",
    unitCostUsd: 1.2,
  },
  "LUM-2X8-JOIST": {
    sku: "LUM-2X8-JOIST",
    name: "2x8 joist stock",
    category: "lumber",
    unit: "lf",
    spec: "SPF #2",
    unitCostUsd: 1.85,
  },
  "LUM-2X10-HDR": {
    sku: "LUM-2X10-HDR",
    name: "2x10 header stock",
    category: "lumber",
    unit: "lf",
    spec: "SPF #2",
    unitCostUsd: 3.15,
  },
  "LUM-2X10-JOIST": {
    sku: "LUM-2X10-JOIST",
    name: "2x10 joist stock",
    category: "lumber",
    unit: "lf",
    spec: "SPF #2",
    unitCostUsd: 2.8,
  },
  "LUM-2X12-JOIST": {
    sku: "LUM-2X12-JOIST",
    name: "2x12 joist stock",
    category: "lumber",
    unit: "lf",
    spec: "SPF #2",
    unitCostUsd: 3.65,
  },
  "LUM-LVL": {
    sku: "LUM-LVL",
    name: "LVL beam",
    category: "lumber",
    unit: "lf",
    spec: "3-1/2 x 9-1/4in laminated veneer lumber",
    unitCostUsd: 12.5,
  },
  "LUM-SILL-SEAL": {
    sku: "LUM-SILL-SEAL",
    name: "Sill seal foam gasket",
    category: "lumber",
    unit: "roll",
    spec: "6in wide polyethylene foam",
    unitCostUsd: 18.5,
  },
  "SHT-OSB-716": {
    sku: "SHT-OSB-716",
    name: "7/16in OSB sheathing",
    category: "lumber",
    unit: "sheet",
    spec: "4x8",
    unitCostUsd: 18.5,
  },

  // ─── STRUCTURAL HARDWARE ──────────────────────────────────────────────────
  "HRD-JOIST-HNGR": {
    sku: "HRD-JOIST-HNGR",
    name: "LUS26 joist hanger",
    category: "hardware",
    unit: "ea",
    spec: "18 ga galvanized, 2x6 joist",
    unitCostUsd: 1.85,
  },
  "HRD-HURR-TIE": {
    sku: "HRD-HURR-TIE",
    name: "H2.5A hurricane tie",
    category: "hardware",
    unit: "ea",
    spec: "18 ga galvanized rafter-to-plate",
    unitCostUsd: 0.95,
  },

  // ─── DRYWALL ──────────────────────────────────────────────────────────────
  "DRY-12-4X8": {
    sku: "DRY-12-4X8",
    name: "1/2in drywall",
    category: "drywall",
    unit: "sheet",
    spec: "4x8 regular",
    unitCostUsd: 14.2,
  },
  "DRY-58-TYPEX": {
    sku: "DRY-58-TYPEX",
    name: "5/8in Type X drywall",
    category: "drywall",
    unit: "sheet",
    spec: "4x8 fire-rated",
    unitCostUsd: 18.5,
  },
  "DRY-MR-4X8": {
    sku: "DRY-MR-4X8",
    name: "1/2in moisture-resistant board",
    category: "drywall",
    unit: "sheet",
    spec: "4x8 green board, baths and kitchens",
    unitCostUsd: 16.8,
  },
  "DRY-CORNER-BEAD": {
    sku: "DRY-CORNER-BEAD",
    name: "Metal corner bead",
    category: "drywall",
    unit: "lf",
    spec: "standard metal 1-1/4in flanges",
    unitCostUsd: 0.42,
  },
  "DRY-MUD": {
    sku: "DRY-MUD",
    name: "Joint compound",
    category: "drywall",
    unit: "ea",
    spec: "4.5 gal all-purpose",
    unitCostUsd: 17.8,
  },
  "DRY-SETTING-COMP": {
    sku: "DRY-SETTING-COMP",
    name: "Setting-type compound",
    category: "drywall",
    unit: "ea",
    spec: "45-min easy sand, 18 lb bag",
    unitCostUsd: 22.0,
  },
  "DRY-TAPE": {
    sku: "DRY-TAPE",
    name: "Paper joint tape",
    category: "drywall",
    unit: "roll",
    spec: "500ft",
    unitCostUsd: 6.4,
  },

  // ─── INSULATION ───────────────────────────────────────────────────────────
  "INS-R13-BATT": {
    sku: "INS-R13-BATT",
    name: "R-13 batt insulation",
    category: "insulation",
    unit: "sf",
    spec: "15in x 93in kraft-faced, 2x4 wall",
    unitCostUsd: 0.68,
  },
  "INS-R15-BATT": {
    sku: "INS-R15-BATT",
    name: "R-15 batt insulation",
    category: "insulation",
    unit: "sf",
    spec: "15in x 93in kraft-faced, 2x4 wall high-density",
    unitCostUsd: 0.85,
  },
  "INS-R21-BATT": {
    sku: "INS-R21-BATT",
    name: "R-21 batt insulation",
    category: "insulation",
    unit: "sf",
    spec: "23in x 93in kraft-faced, 2x6 wall",
    unitCostUsd: 1.15,
  },
  "INS-R38-BATT": {
    sku: "INS-R38-BATT",
    name: "R-38 batt insulation",
    category: "insulation",
    unit: "sf",
    spec: "ceiling, unfaced",
    unitCostUsd: 1.35,
  },
  "INS-RIGID-ISO": {
    sku: "INS-RIGID-ISO",
    name: "Polyiso rigid foam board",
    category: "insulation",
    unit: "sf",
    spec: "2in R-13, foil-faced, 4x8 sheet",
    unitCostUsd: 0.95,
  },
  "INS-SPRAYFOAM": {
    sku: "INS-SPRAYFOAM",
    name: "Expanding foam sealant",
    category: "insulation",
    unit: "ea",
    spec: "12 oz can, air-sealing grade",
    unitCostUsd: 8.5,
  },
  "INS-BAFFLE": {
    sku: "INS-BAFFLE",
    name: "Rafter baffle",
    category: "insulation",
    unit: "ea",
    spec: "22in cardboard, maintains eave ventilation channel",
    unitCostUsd: 1.85,
  },

  // ─── ELECTRICAL ───────────────────────────────────────────────────────────
  "ELE-BOX-1G": {
    sku: "ELE-BOX-1G",
    name: "Single-gang box",
    category: "electrical",
    unit: "ea",
    spec: "18 cu in nail-on",
    unitCostUsd: 1.35,
  },
  "ELE-NM-12-2": {
    sku: "ELE-NM-12-2",
    name: "12-2 NM-B cable",
    category: "electrical",
    unit: "lf",
    spec: "with ground, 20A circuits",
    unitCostUsd: 0.92,
  },
  "ELE-NM-14-2": {
    sku: "ELE-NM-14-2",
    name: "14-2 NM-B cable",
    category: "electrical",
    unit: "lf",
    spec: "with ground, 15A lighting circuits",
    unitCostUsd: 0.61,
  },
  "ELE-PLATE-NAIL": {
    sku: "ELE-PLATE-NAIL",
    name: "Steel nail plate",
    category: "electrical",
    unit: "ea",
    spec: "1-1/2in x 2-5/8in, protects cable/pipe within 1-1/4in of stud face",
    unitCostUsd: 0.42,
  },
  "ELE-RECEP": {
    sku: "ELE-RECEP",
    name: "15A duplex receptacle",
    category: "electrical",
    unit: "ea",
    spec: "specification grade, tamper-resistant",
    unitCostUsd: 1.45,
  },
  "ELE-GFCI": {
    sku: "ELE-GFCI",
    name: "20A GFCI receptacle",
    category: "electrical",
    unit: "ea",
    spec: "self-test, tamper-resistant, with LED indicator",
    unitCostUsd: 16.5,
  },
  "ELE-SWITCH": {
    sku: "ELE-SWITCH",
    name: "Single-pole 15A switch",
    category: "electrical",
    unit: "ea",
    spec: "specification grade",
    unitCostUsd: 2.2,
  },
  "ELE-COVER": {
    sku: "ELE-COVER",
    name: "Decorator cover plate",
    category: "electrical",
    unit: "ea",
    spec: "1-gang, white",
    unitCostUsd: 0.85,
  },
  "ELE-BRKR-15": {
    sku: "ELE-BRKR-15",
    name: "15A single-pole breaker",
    category: "electrical",
    unit: "ea",
    spec: "plug-in, standard",
    unitCostUsd: 8.5,
  },
  "ELE-BRKR-20": {
    sku: "ELE-BRKR-20",
    name: "20A single-pole breaker",
    category: "electrical",
    unit: "ea",
    spec: "plug-in, standard",
    unitCostUsd: 9.5,
  },
  "ELE-PANEL": {
    sku: "ELE-PANEL",
    name: "200A 40-space main panel",
    category: "electrical",
    unit: "ea",
    spec: "200A main breaker, 40/80 circuit, flush",
    unitCostUsd: 285.0,
  },
  "ELE-GFCI-EXT": {
    sku: "ELE-GFCI-EXT",
    name: "Weatherproof GFCI cover (in-use)",
    category: "electrical",
    unit: "ea",
    spec: "1-gang, while-in-use bubble cover",
    unitCostUsd: 6.5,
  },
  "ELE-LED-CAN": {
    sku: "ELE-LED-CAN",
    name: "6in recessed LED wafer",
    category: "electrical",
    unit: "ea",
    spec: "5000K or 3000K, IC-rated, airtight, 650 lm",
    unitCostUsd: 18.5,
  },
  "ELE-BATH-FAN": {
    sku: "ELE-BATH-FAN",
    name: "Bath exhaust fan",
    category: "electrical",
    unit: "ea",
    spec: "110 cfm, 0.6 sone, Energy Star",
    unitCostUsd: 45.0,
  },

  // ─── PLUMBING ─────────────────────────────────────────────────────────────
  "PLM-PEX-12": {
    sku: "PLM-PEX-12",
    name: "1/2in PEX-A tubing",
    category: "plumbing",
    unit: "lf",
    spec: "with ground",
    unitCostUsd: 0.55,
  },
  "PLM-PEX-FIT": {
    sku: "PLM-PEX-FIT",
    name: "1/2in PEX crimp fitting",
    category: "plumbing",
    unit: "ea",
    spec: "brass, 90° elbow or coupling — specify at order",
    unitCostUsd: 1.25,
  },
  "PLM-PEX-MAN": {
    sku: "PLM-PEX-MAN",
    name: "PEX manifold",
    category: "plumbing",
    unit: "ea",
    spec: "10-port brass with shutoffs",
    unitCostUsd: 145.0,
  },
  "PLM-STOP": {
    sku: "PLM-STOP",
    name: "1/2in angle supply stop",
    category: "plumbing",
    unit: "ea",
    spec: "compression, chrome",
    unitCostUsd: 8.5,
  },
  "PLM-PTRAP": {
    sku: "PLM-PTRAP",
    name: "1-1/2in P-trap",
    category: "plumbing",
    unit: "ea",
    spec: "ABS with cleanout",
    unitCostUsd: 7.2,
  },
  "PLM-DWV-90": {
    sku: "PLM-DWV-90",
    name: "3in DWV 90-degree elbow",
    category: "plumbing",
    unit: "ea",
    spec: "PVC schedule 40",
    unitCostUsd: 4.8,
  },
  "PLM-DWV-TEE": {
    sku: "PLM-DWV-TEE",
    name: "3in DWV sanitary tee",
    category: "plumbing",
    unit: "ea",
    spec: "PVC schedule 40",
    unitCostUsd: 7.5,
  },
  "PLM-PVC-3": {
    sku: "PLM-PVC-3",
    name: "3in PVC DWV pipe",
    category: "plumbing",
    unit: "lf",
    spec: "schedule 40",
    unitCostUsd: 4.1,
  },
  "PLM-PVC-2": {
    sku: "PLM-PVC-2",
    name: "2in PVC DWV pipe",
    category: "plumbing",
    unit: "lf",
    spec: "schedule 40",
    unitCostUsd: 2.35,
  },
  "PLM-WAX": {
    sku: "PLM-WAX",
    name: "Wax ring with horn",
    category: "plumbing",
    unit: "ea",
    spec: "standard horn, for floor flange",
    unitCostUsd: 6.0,
  },
  "PLM-HOSE-BIB": {
    sku: "PLM-HOSE-BIB",
    name: "3/4in sillcock hose bib",
    category: "plumbing",
    unit: "ea",
    spec: "anti-siphon, 8in",
    unitCostUsd: 18.5,
  },

  // ─── HVAC ─────────────────────────────────────────────────────────────────
  "HVA-DUCT-FLEX8": {
    sku: "HVA-DUCT-FLEX8",
    name: "8in insulated flex duct",
    category: "hvac",
    unit: "lf",
    spec: "R-8",
    unitCostUsd: 3.9,
  },
  "HVA-TRUNK": {
    sku: "HVA-TRUNK",
    name: "20x8 galvanized trunk duct",
    category: "hvac",
    unit: "lf",
    spec: "26 ga galvanized sheet metal, rectangular",
    unitCostUsd: 14.5,
  },
  "HVA-TAKEOFF": {
    sku: "HVA-TAKEOFF",
    name: "6in flex duct takeoff collar",
    category: "hvac",
    unit: "ea",
    spec: "with damper, trunk to flex",
    unitCostUsd: 8.5,
  },
  "HVA-BOOT": {
    sku: "HVA-BOOT",
    name: "Register boot",
    category: "hvac",
    unit: "ea",
    spec: "4x10 to 6in round",
    unitCostUsd: 8.75,
  },
  "HVA-REGISTER": {
    sku: "HVA-REGISTER",
    name: "4x10 adjustable supply register",
    category: "hvac",
    unit: "ea",
    spec: "two-way deflection, white steel",
    unitCostUsd: 12.5,
  },
  "HVA-GRILLE": {
    sku: "HVA-GRILLE",
    name: "14x20 return air grille",
    category: "hvac",
    unit: "ea",
    spec: "fixed-blade, white steel",
    unitCostUsd: 18.0,
  },
  "HVA-LINESET": {
    sku: "HVA-LINESET",
    name: "Mini-split line set 25ft",
    category: "hvac",
    unit: "ea",
    spec: "3/8in liquid x 3/4in suction, pre-insulated",
    unitCostUsd: 85.0,
  },
  "HVA-COND-PUMP": {
    sku: "HVA-COND-PUMP",
    name: "Condensate pump",
    category: "hvac",
    unit: "ea",
    spec: "1/30 HP, 100 gph, reservoir with float",
    unitCostUsd: 55.0,
  },
  "HVA-THERMO": {
    sku: "HVA-THERMO",
    name: "Programmable thermostat",
    category: "hvac",
    unit: "ea",
    spec: "7-day, 2H/2C, compatible with heat pump",
    unitCostUsd: 48.0,
  },

  // ─── CONCRETE ─────────────────────────────────────────────────────────────
  "CON-READYMIX": {
    sku: "CON-READYMIX",
    name: "Ready-mix concrete",
    category: "concrete",
    unit: "cy",
    spec: "3000 psi",
    unitCostUsd: 168.0,
  },
  "CON-REBAR-4": {
    sku: "CON-REBAR-4",
    name: "#4 rebar",
    category: "concrete",
    unit: "lf",
    spec: "1/2in deformed bar, grade 60",
    unitCostUsd: 0.78,
  },
  "CON-ANCHOR-BOLT": {
    sku: "CON-ANCHOR-BOLT",
    name: "1/2in anchor bolt",
    category: "concrete",
    unit: "ea",
    spec: "1/2in x 10in J-bolt with nut and washer",
    unitCostUsd: 2.8,
  },
  "CON-FORM-STAKE": {
    sku: "CON-FORM-STAKE",
    name: "18in steel form stake",
    category: "concrete",
    unit: "ea",
    spec: "1-1/4in x 18in flat steel",
    unitCostUsd: 1.2,
  },
  "CON-VAPOR-BAR": {
    sku: "CON-VAPOR-BAR",
    name: "6-mil polyethylene vapor barrier",
    category: "concrete",
    unit: "roll",
    spec: "20x100ft (2000 sf per roll)",
    unitCostUsd: 38.0,
  },
  "CON-WIRE-MESH": {
    sku: "CON-WIRE-MESH",
    name: "6x6 W2.9xW2.9 welded wire mesh",
    category: "concrete",
    unit: "roll",
    spec: "5ft x 150ft roll (750 sf)",
    unitCostUsd: 88.0,
  },

  // ─── FASTENERS ────────────────────────────────────────────────────────────
  "FAS-NAIL-16D": {
    sku: "FAS-NAIL-16D",
    name: "16d framing nails",
    category: "fastener",
    unit: "box",
    spec: "5 lb collated",
    unitCostUsd: 24.5,
  },
  "FAS-SCREW-125": {
    sku: "FAS-SCREW-125",
    name: "1-1/4in drywall screws",
    category: "fastener",
    unit: "box",
    spec: "5 lb",
    unitCostUsd: 21.9,
  },

  // ─── ROOFING & ENVELOPE ───────────────────────────────────────────────────
  "ROO-SHINGLE": {
    sku: "ROO-SHINGLE",
    name: "Architectural shingles",
    category: "roofing",
    unit: "sf",
    spec: "30-year laminated, priced per sf covered",
    unitCostUsd: 1.28,
  },
  "ROO-UNDERLAY": {
    sku: "ROO-UNDERLAY",
    name: "Synthetic underlayment",
    category: "roofing",
    unit: "sf",
    spec: "10 sq roll",
    unitCostUsd: 0.19,
  },
  "ROO-DRIP-EDGE": {
    sku: "ROO-DRIP-EDGE",
    name: "2in aluminum drip edge",
    category: "roofing",
    unit: "lf",
    spec: "10ft lengths, white or mill finish",
    unitCostUsd: 0.85,
  },
  "ROO-ICE-WATER": {
    sku: "ROO-ICE-WATER",
    name: "Ice & water shield",
    category: "roofing",
    unit: "roll",
    spec: "36in x 66.7ft, self-adhering (200 sf per roll)",
    unitCostUsd: 85.0,
  },
  "ROO-RIDGE-CAP": {
    sku: "ROO-RIDGE-CAP",
    name: "Hip & ridge cap shingles",
    category: "roofing",
    unit: "lf",
    spec: "priced per lf covered",
    unitCostUsd: 4.5,
  },
  "ROO-STEP-FLASH": {
    sku: "ROO-STEP-FLASH",
    name: "4x4 step flashing",
    category: "roofing",
    unit: "ea",
    spec: "4x4in 26 ga galvanized, per piece",
    unitCostUsd: 0.65,
  },
  "ROO-PIPE-FLASH": {
    sku: "ROO-PIPE-FLASH",
    name: "Lead pipe flashing boot",
    category: "roofing",
    unit: "ea",
    spec: "2-5in adjustable neoprene",
    unitCostUsd: 12.5,
  },
  "ROO-NAILS": {
    sku: "ROO-NAILS",
    name: "Coil roofing nails 1-3/4in",
    category: "roofing",
    unit: "box",
    spec: "7200 count, electro-galvanized",
    unitCostUsd: 38.0,
  },
  "ROO-WRAP": {
    sku: "ROO-WRAP",
    name: "House wrap",
    category: "roofing",
    unit: "roll",
    spec: "9ft x 111ft (1000 sf per roll)",
    unitCostUsd: 95.0,
  },
  "ROO-FLASH-TAPE": {
    sku: "ROO-FLASH-TAPE",
    name: "Flashing tape",
    category: "roofing",
    unit: "roll",
    spec: "4in x 50ft self-adhesive butyl",
    unitCostUsd: 28.0,
  },
  "ROO-SEALANT": {
    sku: "ROO-SEALANT",
    name: "Roofing sealant",
    category: "roofing",
    unit: "tube",
    spec: "10 oz Black Jack / equivalent, paintable",
    unitCostUsd: 8.5,
  },

  // ─── FINISH MATERIALS ─────────────────────────────────────────────────────
  "FIN-PAINT-FLAT": {
    sku: "FIN-PAINT-FLAT",
    name: "Interior latex flat paint",
    category: "finish",
    unit: "gal",
    spec: "ceiling-grade flat, 400 sf/gal coverage",
    unitCostUsd: 18.5,
  },
  "FIN-PAINT-EGGSHELL": {
    sku: "FIN-PAINT-EGGSHELL",
    name: "Interior latex eggshell paint",
    category: "finish",
    unit: "gal",
    spec: "walls, 350 sf/gal coverage",
    unitCostUsd: 22.0,
  },
  "FIN-PAINT-SEMIGLOSS": {
    sku: "FIN-PAINT-SEMIGLOSS",
    name: "Interior latex semi-gloss paint",
    category: "finish",
    unit: "gal",
    spec: "baths and kitchens, 350 sf/gal",
    unitCostUsd: 24.5,
  },
  "FIN-PAINT-CEILING": {
    sku: "FIN-PAINT-CEILING",
    name: "Ceiling paint flat white",
    category: "finish",
    unit: "gal",
    spec: "high-hide flat, 350 sf/gal",
    unitCostUsd: 19.0,
  },
  "FIN-PAINT-TRIM": {
    sku: "FIN-PAINT-TRIM",
    name: "Trim and door enamel",
    category: "finish",
    unit: "gal",
    spec: "semi-gloss alkyd/latex hybrid, 350 sf/gal",
    unitCostUsd: 28.0,
  },
  "FIN-PRIMER-PVA": {
    sku: "FIN-PRIMER-PVA",
    name: "PVA drywall primer",
    category: "finish",
    unit: "gal",
    spec: "new drywall sealer, 400 sf/gal",
    unitCostUsd: 16.5,
  },
  "FIN-PAINT-EXT": {
    sku: "FIN-PAINT-EXT",
    name: "Exterior latex paint",
    category: "finish",
    unit: "gal",
    spec: "100% acrylic, 350 sf/gal",
    unitCostUsd: 32.0,
  },
  "FIN-CAULK": {
    sku: "FIN-CAULK",
    name: "Painter's caulk",
    category: "finish",
    unit: "tube",
    spec: "10 oz siliconized acrylic, paintable",
    unitCostUsd: 3.5,
  },
  "FIN-STAIN": {
    sku: "FIN-STAIN",
    name: "Interior wood stain",
    category: "finish",
    unit: "gal",
    spec: "oil-based penetrating stain",
    unitCostUsd: 24.0,
  },
  "FIN-POLY": {
    sku: "FIN-POLY",
    name: "Oil-based polyurethane",
    category: "finish",
    unit: "gal",
    spec: "gloss/satin, floors and millwork",
    unitCostUsd: 38.0,
  },
  "FIN-CASING": {
    sku: "FIN-CASING",
    name: "Colonial casing 2-1/4in",
    category: "finish",
    unit: "lf",
    spec: "finger-joint pine, primed",
    unitCostUsd: 1.1,
  },
  "FIN-BASEBOARD": {
    sku: "FIN-BASEBOARD",
    name: "Colonial baseboard 3-1/4in",
    category: "finish",
    unit: "lf",
    spec: "finger-joint pine, primed",
    unitCostUsd: 1.35,
  },
  "FIN-CROWN": {
    sku: "FIN-CROWN",
    name: "Crown molding 3-5/8in",
    category: "finish",
    unit: "lf",
    spec: "finger-joint pine, primed",
    unitCostUsd: 2.2,
  },
  "FIN-SHOE": {
    sku: "FIN-SHOE",
    name: "Shoe molding",
    category: "finish",
    unit: "lf",
    spec: "9/16in x 1-3/4in, primed",
    unitCostUsd: 0.48,
  },
  "FIN-DOOR-INT": {
    sku: "FIN-DOOR-INT",
    name: "Interior door prehung",
    category: "finish",
    unit: "ea",
    spec: "2/8 x 6/8 hollow-core, split jamb",
    unitCostUsd: 198.0,
  },
  "FIN-DOOR-HW": {
    sku: "FIN-DOOR-HW",
    name: "Interior door lockset",
    category: "finish",
    unit: "set",
    spec: "passage or privacy, with hinges",
    unitCostUsd: 35.0,
  },
  "FIN-SHELF-CLOSET": {
    sku: "FIN-SHELF-CLOSET",
    name: "Wire closet shelving 12in",
    category: "finish",
    unit: "lf",
    spec: "vinyl-coated steel, with mounting hardware",
    unitCostUsd: 4.5,
  },
  "FIN-LVP": {
    sku: "FIN-LVP",
    name: "Luxury vinyl plank",
    category: "finish",
    unit: "sf",
    spec: "5mm with attached pad, click-lock",
    unitCostUsd: 2.85,
  },
  "FIN-CARPET": {
    sku: "FIN-CARPET",
    name: "Carpet with 7/16in pad",
    category: "finish",
    unit: "sf",
    spec: "mid-grade residential combo price",
    unitCostUsd: 3.2,
  },
  "FIN-TILE": {
    sku: "FIN-TILE",
    name: "12x24 porcelain floor tile",
    category: "finish",
    unit: "sf",
    spec: "rectified, 0.4 PEI rating",
    unitCostUsd: 3.8,
  },
  "FIN-THINSET": {
    sku: "FIN-THINSET",
    name: "Modified thinset mortar",
    category: "finish",
    unit: "ea",
    spec: "50 lb bag, covers ~40 sf at 3/16in",
    unitCostUsd: 24.0,
  },
  "FIN-GROUT": {
    sku: "FIN-GROUT",
    name: "Sanded grout",
    category: "finish",
    unit: "ea",
    spec: "25 lb bag, joints 1/8in and wider",
    unitCostUsd: 18.5,
  },

  // ─── FIXTURES ─────────────────────────────────────────────────────────────
  "FIX-TOILET": {
    sku: "FIX-TOILET",
    name: "Elongated toilet",
    category: "fixture",
    unit: "ea",
    spec: "1.28 gpf, two-piece, ADA height",
    unitCostUsd: 285.0,
  },
  "FIX-VANITY": {
    sku: "FIX-VANITY",
    name: "36in vanity with top",
    category: "fixture",
    unit: "ea",
    spec: "36in shaker with cultured marble top, 4in spread",
    unitCostUsd: 495.0,
  },
  "FIX-SINK-KIT": {
    sku: "FIX-SINK-KIT",
    name: "Stainless undermount kitchen sink",
    category: "fixture",
    unit: "ea",
    spec: "33x22in single bowl 16 gauge",
    unitCostUsd: 185.0,
  },
  "FIX-FAUCET-LAV": {
    sku: "FIX-FAUCET-LAV",
    name: "Lavatory faucet",
    category: "fixture",
    unit: "ea",
    spec: "single-hole, 1.2 gpm, chrome or brushed nickel",
    unitCostUsd: 95.0,
  },
  "FIX-FAUCET-KIT": {
    sku: "FIX-FAUCET-KIT",
    name: "Pull-down kitchen faucet",
    category: "fixture",
    unit: "ea",
    spec: "single-hole, 1.8 gpm, with spray",
    unitCostUsd: 145.0,
  },
  "FIX-TUB-VALVE": {
    sku: "FIX-TUB-VALVE",
    name: "Tub/shower pressure-balance valve",
    category: "fixture",
    unit: "ea",
    spec: "ASSE 1016, with trim kit",
    unitCostUsd: 165.0,
  },
  "FIX-WH-50": {
    sku: "FIX-WH-50",
    name: "50-gallon electric water heater",
    category: "fixture",
    unit: "ea",
    spec: "240V, 4500W, 6-year warranty, top-connect",
    unitCostUsd: 680.0,
  },
  "FIX-HOOD": {
    sku: "FIX-HOOD",
    name: "30in range hood",
    category: "fixture",
    unit: "ea",
    spec: "400 cfm, convertible duct/ductless",
    unitCostUsd: 220.0,
  },
  "FIX-SMOKE": {
    sku: "FIX-SMOKE",
    name: "Smoke alarm",
    category: "fixture",
    unit: "ea",
    spec: "10-year sealed lithium battery, photoelectric",
    unitCostUsd: 28.0,
  },
  "FIX-CO": {
    sku: "FIX-CO",
    name: "Combination smoke/CO alarm",
    category: "fixture",
    unit: "ea",
    spec: "10-year sealed lithium, dual sensor",
    unitCostUsd: 42.0,
  },
  "FIX-LIGHT": {
    sku: "FIX-LIGHT",
    name: "Flush-mount LED light fixture",
    category: "fixture",
    unit: "ea",
    spec: "12in, 1050 lm, 3000K, dimmable",
    unitCostUsd: 65.0,
  },
  "FIX-FAN-CEIL": {
    sku: "FIX-FAN-CEIL",
    name: "52in ceiling fan with light",
    category: "fixture",
    unit: "ea",
    spec: "52in, 5-blade, integrated LED, remote",
    unitCostUsd: 185.0,
  },
};

/** All catalog SKU ids, for iteration and validation. */
export const CATALOG_SKUS = Object.keys(CATALOG);

/**
 * Catalog entries the vision model should look for at a given stage —
 * filtered to the part families that stage's definition declares it expects.
 */
export function expectedSkusForStage(stage: StageId): CatalogEntry[] {
  const cats = new Set<PartCategory>(stageDef(stage).expects);
  return Object.values(CATALOG).filter((e) => cats.has(e.category));
}
